// const postsData = [
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Alexander Frem",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
//   {
//     id: "#123056043",
//     imageUrl: "/src/images/main-post-image.jpg",
//     userAvatarUrl: "/src/images/main-post-user-avatar.jpg",
//     userName: "Saurabh Singh",
//     timestamp: "Oct 29, 2023 ; 13:30",
//     duration: "5:00 min",
//     content:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
//     likes: "250K",
//     comments: 750,
//   },
// ];
