import Cover_Image from "../../../images/trendingPost_coverImg.png";
import Profile_Pic from "../../../images/trendingPost_profile.png";

export default [
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
  {
    commentCount: "750",
    timeToken: "250k",
    postId: "#12356890",
    coverImg: Cover_Image,
    ownerImage: Profile_Pic,
    ownerName: "Alexander Frem",
    date_and_time: "Oct 29,2023 ; 13:30",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ",
  },
];
